name: Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  cd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    defaults:
      run:
        working-directory: ./site

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/dist
